rslider bounds(81.6, 14.4, 72.0, 72.0), channel("MixXIn"), range(0, 1, 0, 1, 0.001), text("MixXIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(153.6, 14.4, 72.0, 72.0), channel("MixYIn"), range(0, 1, 0, 1, 0.001), text("MixYIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(225.6, 14.4, 72.0, 72.0), channel("DelayIn"), range(0, 1, 0, 1, 0.001), text("DelayIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(297.6, 14.4, 72.0, 72.0), channel("LPFIn"), range(0, 1, 0, 1, 0.001), text("LPFIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(369.6, 14.4, 72.0, 72.0), channel("SendAmountIn"), range(0, 1, 0, 1, 0.001), text("SendAmountIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(441.6, 14.4, 72.0, 72.0), channel("DistortAmountIn"), range(0, 1, 0, 1, 0.001), text("DistortAmountIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(513.6, 14.4, 72.0, 72.0), channel("ShapeIn"), range(0, 1, 0, 1, 0.001), text("ShapeIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(585.6, 14.4, 72.0, 72.0), channel("LfoFreqIn"), range(0, 1, 0, 1, 0.001), text("LfoFreqIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(657.6, 14.4, 72.0, 72.0), channel("LfoAmpIn"), range(0, 1, 0, 1, 0.001), text("LfoAmpIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(729.6, 14.4, 72.0, 72.0), channel("SmackidibooIn"), range(0, 1, 0, 1, 0.001), text("SmackidibooIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
rslider bounds(801.6, 14.4, 72.0, 72.0), channel("SmudgirydoobidyIn"), range(0, 1, 0, 1, 0.001), text("SmudgirydoobidyIn"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
label bounds(9.6, 86.4, 72.0, 72.0), channel("label12"), text("MorphX"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 86.4, 72.0, 72.0), channel(\"mod0\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 86.4, 72.0, 72.0), channel(\"mod1\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 86.4, 72.0, 72.0), channel(\"mod2\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 86.4, 72.0, 72.0), channel(\"mod3\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 86.4, 72.0, 72.0), channel(\"mod4\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 86.4, 72.0, 72.0), channel(\"mod5\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 86.4, 72.0, 72.0), channel(\"mod6\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 86.4, 72.0, 72.0), channel(\"mod7\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 86.4, 72.0, 72.0), channel(\"mod8\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 86.4, 72.0, 72.0), channel(\"mod9\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 86.4, 72.0, 72.0), channel(\"mod10\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 158.4, 72.0, 72.0), channel("label24"), text("MorphY"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 158.4, 72.0, 72.0), channel(\"mod11\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 158.4, 72.0, 72.0), channel(\"mod12\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 158.4, 72.0, 72.0), channel(\"mod13\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 158.4, 72.0, 72.0), channel(\"mod14\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 158.4, 72.0, 72.0), channel(\"mod15\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 158.4, 72.0, 72.0), channel(\"mod16\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 158.4, 72.0, 72.0), channel(\"mod17\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 158.4, 72.0, 72.0), channel(\"mod18\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 158.4, 72.0, 72.0), channel(\"mod19\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 158.4, 72.0, 72.0), channel(\"mod20\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 158.4, 72.0, 72.0), channel(\"mod21\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 230.4, 72.0, 72.0), channel("label36"), text("Audiodescriptor1"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 230.4, 72.0, 72.0), channel(\"mod22\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 230.4, 72.0, 72.0), channel(\"mod23\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 230.4, 72.0, 72.0), channel(\"mod24\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 230.4, 72.0, 72.0), channel(\"mod25\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 230.4, 72.0, 72.0), channel(\"mod26\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 230.4, 72.0, 72.0), channel(\"mod27\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 230.4, 72.0, 72.0), channel(\"mod28\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 230.4, 72.0, 72.0), channel(\"mod29\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 230.4, 72.0, 72.0), channel(\"mod30\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 230.4, 72.0, 72.0), channel(\"mod31\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 230.4, 72.0, 72.0), channel(\"mod32\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 302.4, 72.0, 72.0), channel("label48"), text("Audiodescriptor2"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 302.4, 72.0, 72.0), channel(\"mod33\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 302.4, 72.0, 72.0), channel(\"mod34\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 302.4, 72.0, 72.0), channel(\"mod35\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 302.4, 72.0, 72.0), channel(\"mod36\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 302.4, 72.0, 72.0), channel(\"mod37\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 302.4, 72.0, 72.0), channel(\"mod38\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 302.4, 72.0, 72.0), channel(\"mod39\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 302.4, 72.0, 72.0), channel(\"mod40\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 302.4, 72.0, 72.0), channel(\"mod41\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 302.4, 72.0, 72.0), channel(\"mod42\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 302.4, 72.0, 72.0), channel(\"mod43\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 374.4, 72.0, 72.0), channel("label60"), text("Audiodescriptor3"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 374.4, 72.0, 72.0), channel(\"mod44\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 374.4, 72.0, 72.0), channel(\"mod45\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 374.4, 72.0, 72.0), channel(\"mod46\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 374.4, 72.0, 72.0), channel(\"mod47\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 374.4, 72.0, 72.0), channel(\"mod48\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 374.4, 72.0, 72.0), channel(\"mod49\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 374.4, 72.0, 72.0), channel(\"mod50\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 374.4, 72.0, 72.0), channel(\"mod51\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 374.4, 72.0, 72.0), channel(\"mod52\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 374.4, 72.0, 72.0), channel(\"mod53\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 374.4, 72.0, 72.0), channel(\"mod54\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 446.4, 72.0, 72.0), channel("label72"), text("Expression"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 446.4, 72.0, 72.0), channel(\"mod55\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(153.6, 446.4, 72.0, 72.0), channel(\"mod56\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(225.6, 446.4, 72.0, 72.0), channel(\"mod57\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(297.6, 446.4, 72.0, 72.0), channel(\"mod58\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(369.6, 446.4, 72.0, 72.0), channel(\"mod59\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(441.6, 446.4, 72.0, 72.0), channel(\"mod60\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(513.6, 446.4, 72.0, 72.0), channel(\"mod61\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(585.6, 446.4, 72.0, 72.0), channel(\"mod62\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(657.6, 446.4, 72.0, 72.0), channel(\"mod63\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(729.6, 446.4, 72.0, 72.0), channel(\"mod64\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
cabbageCreate "nslider", "bounds(801.6, 446.4, 72.0, 72.0), channel(\"mod65\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
label bounds(9.6, 518.4, 72.0, 72.0), channel("label84"), text("LFO"), fontSize(10), outlineColour(255, 255, 255, 255) colour(249, 179, 255, 255) fontColour("black") align("centre") fontSize(10)
cabbageCreate "nslider", "bounds(81.6, 518.4, 72.0, 72.0), channel(\"mod66\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(81.6, 590.4, 72.0, 72.0), channel("MixXOut"), range(0, 1, 0, 1, 0.001), text("MixXOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(153.6, 518.4, 72.0, 72.0), channel(\"mod67\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(153.6, 590.4, 72.0, 72.0), channel("MixYOut"), range(0, 1, 0, 1, 0.001), text("MixYOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(225.6, 518.4, 72.0, 72.0), channel(\"mod68\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(225.6, 590.4, 72.0, 72.0), channel("DelayOut"), range(0, 1, 0, 1, 0.001), text("DelayOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(297.6, 518.4, 72.0, 72.0), channel(\"mod69\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(297.6, 590.4, 72.0, 72.0), channel("LPFOut"), range(0, 1, 0, 1, 0.001), text("LPFOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(369.6, 518.4, 72.0, 72.0), channel(\"mod70\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(369.6, 590.4, 72.0, 72.0), channel("SendAmountOut"), range(0, 1, 0, 1, 0.001), text("SendAmountOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(441.6, 518.4, 72.0, 72.0), channel(\"mod71\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(441.6, 590.4, 72.0, 72.0), channel("DistortAmountOut"), range(0, 1, 0, 1, 0.001), text("DistortAmountOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(513.6, 518.4, 72.0, 72.0), channel(\"mod72\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(513.6, 590.4, 72.0, 72.0), channel("ShapeOut"), range(0, 1, 0, 1, 0.001), text("ShapeOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(585.6, 518.4, 72.0, 72.0), channel(\"mod73\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(585.6, 590.4, 72.0, 72.0), channel("LfoFreqOut"), range(0, 1, 0, 1, 0.001), text("LfoFreqOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(657.6, 518.4, 72.0, 72.0), channel(\"mod74\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(657.6, 590.4, 72.0, 72.0), channel("LfoAmpOut"), range(0, 1, 0, 1, 0.001), text("LfoAmpOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(729.6, 518.4, 72.0, 72.0), channel(\"mod75\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(729.6, 590.4, 72.0, 72.0), channel("SmackidibooOut"), range(0, 1, 0, 1, 0.001), text("SmackidibooOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)
cabbageCreate "nslider", "bounds(801.6, 518.4, 72.0, 72.0), channel(\"mod76\"), range(0, 999, 0, 1, 0.01), fontSize(\"15\"), _type(\"coeff\")"
rslider bounds(801.6, 590.4, 72.0, 72.0), channel("SmudgirydoobidyOut"), range(0, 1, 0, 1, 0.001), text("SmudgirydoobidyOut"), markerColour(58, 124, 165) outlineColour(223, 181, 248) trackerColour(58, 124, 165) colour(161, 74, 118) textColour(0, 0, 0, 255) trackerThickness(1)