;output parameters___________________________ 

kMixX table 0, giParam_Out
kMixY table 1, giParam_Out
kFreq table 2, giParam_Out
kCutoff table 3, giParam_Out
kLFOFreq table 4, giParam_Out
kGrainRate table 5, giParam_Out


;channels to read parameters from___________________________ 

chnset kMixX, "MixX"
chnset kMixY, "MixY"
chnset kFreq, "Freq"
chnset kCutoff, "Cutoff"
chnset kLFOFreq, "LFOFreq"
chnset kGrainRate, "GrainRate"


;____________________________________ 

